name: sarcasm
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - pyyaml
  - conda
  - scipy=0.19.1
  - scikit-learn
  - pytorch
  - torchvision
  - cpuonly
  - cython
  - future
  - pip:
    - numpy==1.13.1
    - pandas==0.24
    - text-unidecode==1.0
    - emoji==0.4.5
    - vaderSentiment
    - nrclex